#!/usr/bin/env python3
"""Genesis sim2sim evaluator aligned with whole_body_tracking observation definitions.

This script evaluates an exported ONNX policy from this codebase (generated by
`scripts/rsl_rl/play.py` or `MotionOnPolicyRunner`) inside Genesis.

Expected ONNX model:
- input: `obs`, `time_step`
- outputs: `actions`, `joint_pos`, `joint_vel`, `body_pos_w`, `body_quat_w`, `body_lin_vel_w`, `body_ang_vel_w`
- metadata added by `whole_body_tracking.utils.exporter.attach_onnx_metadata`

Example:
    python scripts/rsl_rl/evaluate_sim2sim_genesis.py \
        --policy_path /path/to/policy.onnx \
        --urdf_file source/whole_body_tracking/whole_body_tracking/assets/unitree_description/urdf/g1/main.urdf \
        --motion_file /path/to/motion.npz \
        --num_envs 64 \
        --backend cpu \
        --policy_device cpu \
        --seed 42 \
        --output_csv logs/sim2sim_eval/g1_genesis_eval.csv
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import random
import xml.etree.ElementTree as ET
from collections import defaultdict, deque
from dataclasses import dataclass
from datetime import datetime
from typing import Any

import numpy as np
import onnx
import onnxruntime as ort
import torch
from onnx import numpy_helper

try:
    from tqdm.auto import tqdm
except ImportError:
    tqdm = None

NEXT_LAB_DATE = "2026.06.03"

def _parse_csv_list(value: str | None, cast_type: Any = str) -> list[Any]:
    if value is None or value == "":
        return []
    items = [item for item in value.split(",") if item != ""]
    if cast_type is str:
        return items
    if cast_type is int:
        # Metadata may encode integers with decimal formatting (e.g., "1.000").
        return [int(round(float(item))) for item in items]
    return [cast_type(item) for item in items]


def _load_onnx_metadata(path: str) -> dict[str, str]:
    model = onnx.load(path)
    return {entry.key: entry.value for entry in model.metadata_props}


def _infer_reference_length_from_policy(path: str) -> int | None:
    """Infer reference motion length encoded in exported ONNX policy."""
    model = onnx.load(path)
    graph = model.graph
    input_names = {inp.name for inp in graph.input}
    if "time_step" not in input_names:
        return None

    producer_by_output: dict[str, onnx.NodeProto] = {}
    for node in graph.node:
        for out_name in node.output:
            producer_by_output[out_name] = node

    scalar_constants: dict[str, float] = {}
    for init in graph.initializer:
        arr = np.asarray(numpy_helper.to_array(init))
        if arr.size == 1:
            scalar_constants[init.name] = float(arr.reshape(()))

    for node in graph.node:
        if node.op_type != "Constant":
            continue
        if len(node.output) != 1:
            continue
        for attr in node.attribute:
            if attr.name != "value" or not attr.HasField("t"):
                continue
            arr = np.asarray(numpy_helper.to_array(attr.t))
            if arr.size == 1:
                scalar_constants[node.output[0]] = float(arr.reshape(()))

    depends_cache: dict[str, bool] = {}

    def _depends_on_time_step(tensor_name: str) -> bool:
        if tensor_name == "time_step":
            return True
        if tensor_name in depends_cache:
            return depends_cache[tensor_name]

        producer = producer_by_output.get(tensor_name)
        if producer is None:
            depends_cache[tensor_name] = False
            return False

        depends = any(
            _depends_on_time_step(inp_name) for inp_name in producer.input if inp_name != ""
        )
        depends_cache[tensor_name] = depends
        return depends

    candidates: list[int] = []

    def _append_candidate(value: float):
        rounded = int(round(value))
        if abs(value - rounded) > 1e-5 or rounded < 0:
            return
        # Exported policy clamps `time_step` to `time_step_total - 1`.
        candidates.append(rounded + 1)

    for node in graph.node:
        if node.op_type == "Clip":
            if len(node.input) < 3:
                continue
            x_name, _, max_name = node.input[:3]
            if x_name and _depends_on_time_step(x_name) and max_name in scalar_constants:
                _append_candidate(scalar_constants[max_name])
            continue

        if node.op_type == "Min":
            if len(node.input) != 2:
                continue
            a_name, b_name = node.input
            a_depends = a_name != "" and _depends_on_time_step(a_name)
            b_depends = b_name != "" and _depends_on_time_step(b_name)
            if a_depends == b_depends:
                continue
            const_name = b_name if a_depends else a_name
            if const_name in scalar_constants:
                _append_candidate(scalar_constants[const_name])

    if not candidates:
        return None
    return max(candidates)


def quat_conjugate_wxyz(q: np.ndarray) -> np.ndarray:
    out = q.copy()
    out[..., 1:] *= -1.0
    return out


def quat_normalize_wxyz(q: np.ndarray) -> np.ndarray:
    norm = np.linalg.norm(q, axis=-1, keepdims=True)
    norm = np.maximum(norm, 1e-8)
    return q / norm


def quat_mul_wxyz(q1: np.ndarray, q2: np.ndarray) -> np.ndarray:
    w1, x1, y1, z1 = np.moveaxis(q1, -1, 0)
    w2, x2, y2, z2 = np.moveaxis(q2, -1, 0)
    w = w1 * w2 - x1 * x2 - y1 * y2 - z1 * z2
    x = w1 * x2 + x1 * w2 + y1 * z2 - z1 * y2
    y = w1 * y2 - x1 * z2 + y1 * w2 + z1 * x2
    z = w1 * z2 + x1 * y2 - y1 * x2 + z1 * w2
    return np.stack([w, x, y, z], axis=-1)


def quat_rotate_wxyz(q: np.ndarray, v: np.ndarray) -> np.ndarray:
    q_xyz = q[..., 1:]
    q_w = q[..., :1]
    t = 2.0 * np.cross(q_xyz, v)
    return v + q_w * t + np.cross(q_xyz, t)


def quat_rotate_inverse_wxyz(q: np.ndarray, v: np.ndarray) -> np.ndarray:
    return quat_rotate_wxyz(quat_conjugate_wxyz(q), v)


def quat_to_matrix_wxyz(q: np.ndarray) -> np.ndarray:
    qn = quat_normalize_wxyz(q)
    w, x, y, z = np.moveaxis(qn, -1, 0)

    ww = w * w
    xx = x * x
    yy = y * y
    zz = z * z
    wx = w * x
    wy = w * y
    wz = w * z
    xy = x * y
    xz = x * z
    yz = y * z

    m00 = ww + xx - yy - zz
    m01 = 2.0 * (xy - wz)
    m02 = 2.0 * (xz + wy)

    m10 = 2.0 * (xy + wz)
    m11 = ww - xx + yy - zz
    m12 = 2.0 * (yz - wx)

    m20 = 2.0 * (xz - wy)
    m21 = 2.0 * (yz + wx)
    m22 = ww - xx - yy + zz

    return np.stack(
        [
            np.stack([m00, m01, m02], axis=-1),
            np.stack([m10, m11, m12], axis=-1),
            np.stack([m20, m21, m22], axis=-1),
        ],
        axis=-2,
    )


def quat_error_magnitude_wxyz(q_ref: np.ndarray, q_cur: np.ndarray) -> np.ndarray:
    q_ref_n = quat_normalize_wxyz(q_ref)
    q_cur_n = quat_normalize_wxyz(q_cur)
    dot = np.sum(q_ref_n * q_cur_n, axis=-1)
    dot = np.clip(np.abs(dot), -1.0, 1.0)
    return 2.0 * np.arccos(dot)


def yaw_quat_wxyz(q: np.ndarray) -> np.ndarray:
    w, x, y, z = q
    yaw = np.arctan2(2.0 * (w * z + x * y), 1.0 - 2.0 * (y * y + z * z))
    return np.array([np.cos(yaw * 0.5), 0.0, 0.0, np.sin(yaw * 0.5)], dtype=np.float32)


# Matches tracking_env_cfg policy observation corruption (AdditiveUniformNoiseCfg).
OBS_NOISE_UNIFORM_RANGES: dict[str, tuple[float, float]] = {
    "motion_anchor_pos_b": (-0.25, 0.25),
    "motion_anchor_ori_b": (-0.05, 0.05),
    "base_lin_vel": (-0.5, 0.5),
    "base_ang_vel": (-0.2, 0.2),
    "joint_pos": (-0.01, 0.01),
    "joint_vel": (-0.5, 0.5),
}

# Matches tracking_env_cfg.EventCfg startup/interval randomization.
DOMAIN_RAND_FRICTION_RANGE = (0.3, 1.6)
DOMAIN_RAND_FRICTION_NUM_BUCKETS = 64
DOMAIN_RAND_JOINT_DEFAULT_POS_RANGE = (-0.00, 0.00)
DOMAIN_RAND_BASE_COM_RANGE = {
    "x": (-0.025, 0.025),
    "y": (-0.05, 0.05),
    "z": (-0.05, 0.05),
}
DOMAIN_RAND_PUSH_INTERVAL_RANGE_S = (1.0, 3.0)
DOMAIN_RAND_PUSH_VELOCITY_RANGE = {
    "x": (-0.5, 0.5),
    "y": (-0.5, 0.5),
    "z": (-0.2, 0.2),
    "roll": (-0.52, 0.52),
    "pitch": (-0.52, 0.52),
    "yaw": (-0.78, 0.78),
    # "x": (-0.0, 0.0),
    # "y": (-0.0, 0.0),
    # "z": (-0.0, 0.0),
    # "roll": (-0.0, 0.0),
    # "pitch": (-0.0, 0.0),
    # "yaw": (-0.0, 0.0),
}


def _bucketize_uniform(values: np.ndarray, low: float, high: float, num_buckets: int) -> np.ndarray:
    if num_buckets <= 1 or high <= low:
        return values.astype(np.float32)
    idx = np.round((values - low) / (high - low) * (num_buckets - 1)).astype(np.int32)
    idx = np.clip(idx, 0, num_buckets - 1)
    bucket_values = np.linspace(low, high, num_buckets, dtype=np.float32)
    return bucket_values[idx]


G1_ALL_BODY_JOINT_NAMES = (
    "root_joint",
    "left_hip_pitch_joint",
    "left_hip_roll_joint",
    "left_hip_yaw_joint",
    "left_knee_joint",
    "left_ankle_pitch_joint",
    "left_ankle_roll_joint",
    "right_hip_pitch_joint",
    "right_hip_roll_joint",
    "right_hip_yaw_joint",
    "right_knee_joint",
    "right_ankle_pitch_joint",
    "right_ankle_roll_joint",
    "waist_yaw_joint",
    "waist_roll_joint",
    "waist_pitch_joint",
    "left_shoulder_pitch_joint",
    "left_shoulder_roll_joint",
    "left_shoulder_yaw_joint",
    "left_elbow_joint",
    "left_wrist_roll_joint",
    "left_wrist_pitch_joint",
    "left_wrist_yaw_joint",
    "right_shoulder_pitch_joint",
    "right_shoulder_roll_joint",
    "right_shoulder_yaw_joint",
    "right_elbow_joint",
    "right_wrist_roll_joint",
    "right_wrist_pitch_joint",
    "right_wrist_yaw_joint",
)


def _resolve_urdf_child_link_names(urdf_file: str | None, joint_names: tuple[str, ...]) -> list[str] | None:
    if urdf_file is None or not os.path.isfile(urdf_file):
        return None
    try:
        robot_root = ET.parse(urdf_file).getroot()
    except Exception:
        return None

    child_link_by_joint: dict[str, str] = {}
    all_link_names: list[str] = []
    child_link_names: set[str] = set()
    for link_el in robot_root.findall("link"):
        link_name = link_el.get("name")
        if link_name is not None:
            all_link_names.append(link_name)
    for joint_el in robot_root.findall("joint"):
        joint_name = joint_el.get("name")
        child_el = joint_el.find("child")
        if joint_name is None or child_el is None:
            continue
        child_name = child_el.get("link")
        if child_name is not None:
            child_link_by_joint[joint_name] = child_name
            child_link_names.add(child_name)

    root_link_name = None
    for link_name in all_link_names:
        if link_name not in child_link_names:
            root_link_name = link_name
            break

    resolved_links: list[str] = []
    for joint_name in joint_names:
        child_name = child_link_by_joint.get(joint_name)
        if child_name is None and joint_name == "root_joint":
            child_name = root_link_name
        if child_name is None:
            return None
        if child_name not in resolved_links:
            resolved_links.append(child_name)
    return resolved_links


def _compute_error_vel(joints_gt: np.ndarray, joints_pred: np.ndarray) -> np.ndarray:
    if joints_gt.shape[0] < 2:
        return np.empty((0,), dtype=np.float32)
    vel_gt = joints_gt[1:] - joints_gt[:-1]
    vel_pred = joints_pred[1:] - joints_pred[:-1]
    normed = np.linalg.norm(vel_pred - vel_gt, axis=2)
    return np.mean(normed, axis=1).astype(np.float32)


def _compute_error_accel(joints_gt: np.ndarray, joints_pred: np.ndarray) -> np.ndarray:
    if joints_gt.shape[0] < 3:
        return np.empty((0,), dtype=np.float32)
    accel_gt = joints_gt[:-2] - 2.0 * joints_gt[1:-1] + joints_gt[2:]
    accel_pred = joints_pred[:-2] - 2.0 * joints_pred[1:-1] + joints_pred[2:]
    normed = np.linalg.norm(accel_pred - accel_gt, axis=2)
    return np.mean(normed, axis=1).astype(np.float32)


def _compute_metrics_lite(pred_pos: np.ndarray, gt_pos: np.ndarray, root_idx: int = 0) -> dict[str, np.ndarray]:
    if pred_pos.shape != gt_pos.shape:
        raise ValueError(f"pred/gt shape mismatch: {pred_pos.shape} vs {gt_pos.shape}")
    if pred_pos.ndim != 3:
        raise ValueError(f"Expected [T, B, 3] body positions, got shape={pred_pos.shape}")

    mpjpe_g = np.linalg.norm(gt_pos - pred_pos, axis=2) * 1000.0
    vel_dist = _compute_error_vel(pred_pos, gt_pos) * 1000.0
    accel_dist = _compute_error_accel(pred_pos, gt_pos) * 1000.0

    pred_local = pred_pos - pred_pos[:, [root_idx]]
    gt_local = gt_pos - gt_pos[:, [root_idx]]
    mpjpe_l = np.linalg.norm(gt_local - pred_local, axis=2) * 1000.0

    return {
        "mpjpe_g": mpjpe_g.astype(np.float32),
        "mpjpe_l": mpjpe_l.astype(np.float32),
        "vel_dist": vel_dist.astype(np.float32),
        "accel_dist": accel_dist.astype(np.float32),
    }


# Kp/Kd perturbation RNG (Gaussian scale 0.27). Uses this seed only, not `--seed` / `--evaluation_seed`.
_EVAL_KP_KD_PERTURB_RNG_SEED = 913_571


@dataclass
class PolicyMeta:
    joint_names: list[str]
    default_joint_pos: np.ndarray
    joint_stiffness: np.ndarray
    joint_damping: np.ndarray
    action_scale: np.ndarray
    observation_names: list[str]
    observation_history_lengths: list[int]
    body_names: list[str]
    anchor_body_name: str


def _parse_policy_meta(raw_meta: dict[str, str]) -> PolicyMeta:
    required = [
        "joint_names",
        "default_joint_pos",
        "joint_stiffness",
        "joint_damping",
        "action_scale",
        "observation_names",
        "body_names",
        "anchor_body_name",
    ]
    missing = [key for key in required if key not in raw_meta]
    if missing:
        raise RuntimeError(
            "Missing ONNX metadata keys: "
            f"{missing}. Re-export policy with `attach_onnx_metadata` from this codebase."
        )

    observation_names = _parse_csv_list(raw_meta["observation_names"], str)
    history_lengths = _parse_csv_list(raw_meta.get("observation_history_lengths"), int)
    if len(history_lengths) != len(observation_names):
        history_lengths = [1] * len(observation_names)

    # Perturbing the joint stiffness and damping by 5% for distribution shift
    joint_stiffness_orig = np.array(_parse_csv_list(raw_meta["joint_stiffness"], float), dtype=np.float32)
    joint_damping_orig = np.array(_parse_csv_list(raw_meta["joint_damping"], float), dtype=np.float32)
    kp_kd_rng = np.random.default_rng(_EVAL_KP_KD_PERTURB_RNG_SEED)
    joint_stiffness_final = joint_stiffness_orig * (1.0 + 0.27 * kp_kd_rng.standard_normal(joint_stiffness_orig.shape))
    joint_damping_final = joint_damping_orig * (1.0 + 0.27 * kp_kd_rng.standard_normal(joint_damping_orig.shape))
    return PolicyMeta(
        joint_names=_parse_csv_list(raw_meta["joint_names"], str),
        default_joint_pos=np.array(_parse_csv_list(raw_meta["default_joint_pos"], float), dtype=np.float32),
        joint_stiffness=joint_stiffness_final,
        joint_damping=joint_damping_final,
        action_scale=np.array(_parse_csv_list(raw_meta["action_scale"], float), dtype=np.float32),
        observation_names=observation_names,
        observation_history_lengths=[max(int(v), 1) for v in history_lengths],
        body_names=_parse_csv_list(raw_meta["body_names"], str),
        anchor_body_name=raw_meta["anchor_body_name"],
    )


def _add_robot_entity(gs_module: Any, scene: Any, urdf_file: str | None, xml_file: str | None):
    """Create Genesis robot entity, preferring URDF and falling back to MJCF XML."""
    if urdf_file is not None:
        urdf_ctor = getattr(gs_module.morphs, "URDF", None)
        if urdf_ctor is None:
            raise RuntimeError("Genesis build does not expose gs.morphs.URDF. Provide --xml_file instead.")

        candidate_kwargs = [
            {"file": urdf_file, "pos": (0.0, 0.0, 0.0)},
            {"file": urdf_file},
            {"urdf_file": urdf_file, "pos": (0.0, 0.0, 0.0)},
            {"urdf_file": urdf_file},
            {"urdf_path": urdf_file, "pos": (0.0, 0.0, 0.0)},
            {"urdf_path": urdf_file},
        ]
        last_error = None
        for kwargs in candidate_kwargs:
            try:
                return scene.add_entity(urdf_ctor(**kwargs))
            except TypeError as exc:
                last_error = exc
                continue
        raise RuntimeError(f"Could not construct Genesis URDF morph for '{urdf_file}': {last_error}")

    if xml_file is not None:
        return scene.add_entity(
            gs_module.morphs.MJCF(
                file=xml_file,
                pos=(0.0, 0.0, 0.0),
                default_armature=0.0,
            )
        )

    raise ValueError("Provide either --urdf_file (recommended) or --xml_file.")


def _apply_global_random_seeds(seed: int) -> None:
    """Align Python / NumPy / torch RNG streams for repeatable evaluation."""

    seed = int(seed)
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
        torch.backends.cudnn.benchmark = False
        torch.backends.cudnn.deterministic = True


class Sim2SimEvaluatorGenesis:
    def __init__(
        self,
        policy_path: str,
        urdf_file: str | None,
        xml_file: str | None,
        motion_file: str | None,
        backend: str,
        policy_device: str,
        sim_dt: float,
        control_dt: float,
        max_steps: int | None,
        start_timestep: int,
        torque_limit: float | None,
        record_video: bool,
        viewer: bool,
        num_envs: int,
        show_reference: bool,
        reference_marker_radius: float,
        output_motion_npz: str | None,
        target_trajectories: int,
        record_motion: bool,
        compute_metrics: bool,
        metric_num_envs: int,
        add_noise: bool,
        domain_randomization: bool,
        experiment_seed: int | None = None,
    ):
        try:
            import genesis as gs
        except ImportError as exc:
            raise ImportError(
                "Genesis is required to run this script. Install Genesis in the current Python environment."
            ) from exc

        if not policy_path.endswith(".onnx"):
            raise ValueError("This evaluator expects an ONNX policy exported by this codebase.")

        self.policy_path = policy_path
        self.motion_file = motion_file
        self.sim_dt = sim_dt
        self.control_dt = control_dt
        self.record_video = record_video
        self.viewer = viewer
        self.torque_limit = torque_limit
        self.start_timestep = int(start_timestep)
        self.num_envs = max(int(num_envs), 1)
        self.show_reference = show_reference
        self.reference_marker_radius = reference_marker_radius
        self.output_motion_npz = output_motion_npz
        self.target_trajectories = max(int(target_trajectories), 1)
        self.record_motion = bool(record_motion)
        self.compute_metrics = bool(compute_metrics)
        self.metric_num_envs = max(int(metric_num_envs), 1)
        if self.record_motion:
            # Motion logging mode always computes metrics on exactly the requested
            # number of trajectory episodes.
            self.compute_metrics = True
            self.metric_num_envs = self.target_trajectories
        self.add_noise = bool(add_noise)
        self.domain_randomization = bool(domain_randomization)
        self.experiment_seed = int(experiment_seed) if experiment_seed is not None else None
        if self.experiment_seed is not None:
            _apply_global_random_seeds(self.experiment_seed)
        self._rng = np.random.default_rng(self.experiment_seed)

        ratio = control_dt / sim_dt
        if abs(ratio - round(ratio)) > 1e-6:
            raise ValueError(f"control_dt/sim_dt must be an integer. Got control_dt={control_dt}, sim_dt={sim_dt}")
        self.sim_decimation = int(round(ratio))

        # ONNX + metadata
        self.meta = _parse_policy_meta(_load_onnx_metadata(policy_path))
        self.num_joints = len(self.meta.joint_names)
        self.num_actions = len(self.meta.action_scale)

        if self.num_actions != self.num_joints:
            raise RuntimeError(
                f"Unsupported action/joint mismatch: action_dim={self.num_actions}, joint_dim={self.num_joints}."
            )
        if len(self.meta.default_joint_pos) != self.num_joints:
            raise RuntimeError("default_joint_pos length does not match joint_names.")

        available_providers = ort.get_available_providers()
        use_cuda = policy_device.startswith("cuda") and "CUDAExecutionProvider" in available_providers
        providers = ["CUDAExecutionProvider", "CPUExecutionProvider"] if use_cuda else ["CPUExecutionProvider"]
        if self.experiment_seed is not None:
            sess_opts = ort.SessionOptions()
            sess_opts.execution_mode = ort.ExecutionMode.ORT_SEQUENTIAL
            sess_opts.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_ALL
            sess_opts.enable_mem_pattern = False
            sess_opts.enable_cpu_mem_arena = False
            sess_opts.intra_op_num_threads = 1
            sess_opts.inter_op_num_threads = 1
            self.session = ort.InferenceSession(
                policy_path, sess_options=sess_opts, providers=providers
            )
        else:
            self.session = ort.InferenceSession(policy_path, providers=providers)
        input_names = [inp.name for inp in self.session.get_inputs()]
        if "obs" not in input_names:
            raise RuntimeError(f"ONNX input 'obs' not found. Inputs={input_names}")
        if "time_step" not in input_names:
            raise RuntimeError(f"ONNX input 'time_step' not found. Inputs={input_names}")
        self.obs_input_name = "obs"
        self.time_input_name = "time_step"

        output_names = [out.name for out in self.session.get_outputs()]
        required_outputs = {"actions", "joint_pos", "joint_vel", "body_pos_w", "body_quat_w", "body_lin_vel_w", "body_ang_vel_w"}
        if not required_outputs.issubset(set(output_names)):
            raise RuntimeError(f"ONNX outputs missing required names. Found={output_names}")
        self.output_names = output_names

        self.term_dims = self._build_term_dims()
        self.obs_dim_expected = self._compute_obs_dim()
        self.zero_obs = np.zeros((1, self.obs_dim_expected), dtype=np.float32)
        self.last_action = np.zeros((self.num_envs, self.num_actions), dtype=np.float32)
        self._init_history()
        self._default_joint_pos_by_env = np.repeat(self.meta.default_joint_pos[None, :], self.num_envs, axis=0).astype(
            np.float32
        )
        self._push_next_step_by_env = np.full(self.num_envs, np.iinfo(np.int32).max, dtype=np.int32)
        self._push_root_dofs: list[int] = []

        # Optional motion action for Delta-A open-loop setup.
        self.motion_actions: np.ndarray | None = None
        if motion_file is not None:
            data = np.load(motion_file)
            if "action" in data.files:
                self.motion_actions = data["action"].astype(np.float32)
            elif "actions" in data.files:
                self.motion_actions = data["actions"].astype(np.float32)

        self.requires_motion_action = "motion_joint_action" in self.meta.observation_names
        if self.requires_motion_action and self.motion_actions is None:
            raise RuntimeError(
                "Policy observation includes 'motion_joint_action' but motion file with `action`/`actions` is not provided."
            )

        self.reference_motion_length_steps = _infer_reference_length_from_policy(policy_path)
        if self.reference_motion_length_steps is None or self.reference_motion_length_steps <= 0:
            raise RuntimeError(
                "Failed to infer reference motion length from exported ONNX policy. "
                "Re-export the policy with this codebase's motion exporter."
            )
        if self.start_timestep < 0:
            raise ValueError(f"--start_timestep must be >= 0. Got {self.start_timestep}.")
        if self.start_timestep >= self.reference_motion_length_steps:
            raise ValueError(
                f"--start_timestep={self.start_timestep} is out of range for reference length "
                f"{self.reference_motion_length_steps}."
            )

        # Rollout horizon is the remaining reference motion from start_timestep to end.
        self.max_steps = self.reference_motion_length_steps - self.start_timestep
        if max_steps is not None and int(max_steps) != self.max_steps:
            # print(
            #     f"[WARN] Ignoring --max_steps={int(max_steps)}; using policy reference window "
            #     f"from start_timestep={self.start_timestep} with "
            #     f"{self.max_steps} steps."
            # )
            self.max_steps = int(max_steps)
            print(f"max_steps: {self.max_steps}")
        # Genesis init
        gs_backend = gs.gpu if backend == "gpu" else gs.cpu
        if self.experiment_seed is not None:
            try:
                gs.init(
                    backend=gs_backend,
                    precision="32",
                    logging_level="warning",
                    seed=self.experiment_seed,
                )
                print(f"[INFO]: Genesis gs.init seeded with evaluation_seed={self.experiment_seed}.")
            except TypeError as exc:
                gs.init(backend=gs_backend, precision="32", logging_level="warning")
                print(
                    "[WARN]: This Genesis build does not accept `seed` in gs.init(...); "
                    f"physics RNG may not match across runs ({exc})."
                )
        else:
            gs.init(backend=gs_backend, precision="32", logging_level="warning")
        rigid_options_kwargs: dict[str, Any] = {"enable_self_collision": False}
        if self.domain_randomization:
            # Genesis requires batched link/dof info for physics randomization calls.
            rigid_options_kwargs.update({"batch_dofs_info": True, "batch_links_info": True})
        try:
            rigid_options = gs.options.RigidOptions(**rigid_options_kwargs)
        except TypeError:
            rigid_options_kwargs.pop("batch_dofs_info", None)
            rigid_options_kwargs.pop("batch_links_info", None)
            rigid_options = gs.options.RigidOptions(**rigid_options_kwargs)
            if self.domain_randomization:
                print(
                    "[WARN] Current Genesis build does not accept batch_dofs_info/batch_links_info; "
                    "domain randomization coverage may be reduced."
                )
        self.scene = gs.Scene(
            sim_options=gs.options.SimOptions(dt=self.sim_dt, substeps=1, gravity=(0.0, 0.0, -9.81)),
            rigid_options=rigid_options,
            show_viewer=self.viewer,
            renderer=gs.renderers.Rasterizer(),
        )
        self.scene.add_entity(gs.morphs.Plane())
        self.robot = _add_robot_entity(gs, self.scene, urdf_file=urdf_file, xml_file=xml_file)

        # Visual reference markers: one white sphere per reference body position.
        self.reference_markers = []
        if self.show_reference:
            for _ in self.meta.body_names:
                marker = self.scene.add_entity(
                    gs.morphs.Sphere(
                        radius=self.reference_marker_radius,
                        collision=False,
                        fixed=True,
                    ),
                    surface=gs.surfaces.Default(color=(1.0, 1.0, 1.0)),
                )
                self.reference_markers.append(marker)

        self.cam = None
        if self.record_video:
            self.cam = self.scene.add_camera(
                res=(1280, 720),
                pos=(3.0, 0.0, 2.0),
                lookat=(0.0, 0.0, 0.8),
                fov=45,
                GUI=False,
            )

        if self.num_envs > 1:
            self.scene.build(n_envs=self.num_envs, env_spacing=(2.5, 2.5))
        else:
            self.scene.build()

        # Joint + link mapping
        self.joint_qs_indices: list[int] = []
        self.joint_dof_indices: list[int] = []
        for name in self.meta.joint_names:
            joint = self.robot.get_joint(name)
            if len(joint.qs_idx_local) != 1 or len(joint.dofs_idx_local) != 1:
                raise RuntimeError(f"Only 1-DoF joints are supported. Joint '{name}' has multiple DoFs.")
            self.joint_qs_indices.append(int(joint.qs_idx_local[0]))
            self.joint_dof_indices.append(int(joint.dofs_idx_local[0]))

        self.body_links = [self.robot.get_link(name) for name in self.meta.body_names]
        self.log_body_names = list(self.meta.body_names)
        self.log_body_links = list(self.body_links)
        if urdf_file is not None:
            all_g1_body_names = _resolve_urdf_child_link_names(urdf_file, G1_ALL_BODY_JOINT_NAMES)
            if all_g1_body_names is not None:
                try:
                    self.log_body_links = [self.robot.get_link(name) for name in all_g1_body_names]
                    self.log_body_names = list(all_g1_body_names)
                    print(
                        f"[INFO] Logging full G1 body set from URDF joints: {len(self.log_body_names)} bodies "
                        f"(policy tracking still uses {len(self.meta.body_names)} metadata bodies)."
                    )
                except Exception as exc:
                    print(
                        "[WARN] Failed to enable full G1 body logging; "
                        f"falling back to metadata body set ({len(self.meta.body_names)}). Error: {exc}"
                    )
        self.anchor_idx = self.meta.body_names.index(self.meta.anchor_body_name)
        self.root_idx = 0
        self.ee_body_names = {
            "left_ankle_roll_link",
            "right_ankle_roll_link",
            "left_wrist_yaw_link",
            "right_wrist_yaw_link",
        }
        self.ee_body_indices = [i for i, name in enumerate(self.meta.body_names) if name in self.ee_body_names]
        self.traj_data_keys = (
            "joint_pos",
            "joint_vel",
            "body_pos_w",
            "body_quat_w",
            "body_lin_vel_w",
            "body_ang_vel_w",
            "action",
        )
        self._setup_domain_randomization()

    def _default_joint_pos_for_batch(self, batch_size: int) -> np.ndarray:
        if batch_size <= 0:
            raise ValueError(f"Expected positive batch size, got {batch_size}.")
        if self._default_joint_pos_by_env.shape[0] == batch_size:
            return self._default_joint_pos_by_env
        if self._default_joint_pos_by_env.shape[0] == 1:
            return np.repeat(self._default_joint_pos_by_env, batch_size, axis=0)
        if batch_size == 1:
            return self._default_joint_pos_by_env[:1]
        raise RuntimeError(
            "Joint-default-pos randomization batch mismatch: "
            f"have {self._default_joint_pos_by_env.shape[0]} env defaults, requested batch={batch_size}."
        )

    def _call_link_randomization(self, method_name: str, values: np.ndarray, links_idx_local: list[int]) -> bool:
        method = getattr(self.robot, method_name, None)
        if method is None:
            return False

        candidates = [np.asarray(values, dtype=np.float32)]
        if self.num_envs == 1 and candidates[0].ndim >= 2:
            candidates.append(candidates[0][0])

        for candidate in candidates:
            candidate_f32 = np.asarray(candidate, dtype=np.float32)
            for payload in (candidate_f32, torch.from_numpy(candidate_f32)):
                try:
                    method(payload, links_idx_local)
                    return True
                except Exception:
                    continue
        return False

    def _resolve_push_root_dofs(self) -> list[int]:
        # Prefer explicit free-root joint names.
        for root_joint_name in ("root_joint", "floating_base", "base_joint"):
            try:
                joint = self.robot.get_joint(root_joint_name)
                dof_ids = [int(i) for i in joint.dofs_idx_local]
                if len(dof_ids) >= 6:
                    return dof_ids[:6]
            except Exception:
                continue

        n_dofs = int(getattr(self.robot, "n_dofs", len(self.joint_dof_indices) + 6))
        actuated = {int(i) for i in self.joint_dof_indices}
        free_like = [i for i in range(n_dofs) if i not in actuated]
        if len(free_like) >= 6:
            return free_like[:6]
        return []

    def _schedule_next_push(self, env_ids: np.ndarray, current_step: int):
        if env_ids.size == 0:
            return
        low_s, high_s = DOMAIN_RAND_PUSH_INTERVAL_RANGE_S
        interval_s = self._rng.uniform(low_s, high_s, size=env_ids.size)
        interval_steps = np.maximum(1, np.round(interval_s / self.control_dt).astype(np.int32))
        self._push_next_step_by_env[env_ids] = current_step + interval_steps

    def _sample_push_velocity(self, count: int) -> np.ndarray:
        vr = DOMAIN_RAND_PUSH_VELOCITY_RANGE
        return np.stack(
            [
                self._rng.uniform(vr["x"][0], vr["x"][1], size=count),
                self._rng.uniform(vr["y"][0], vr["y"][1], size=count),
                self._rng.uniform(vr["z"][0], vr["z"][1], size=count),
                self._rng.uniform(vr["roll"][0], vr["roll"][1], size=count),
                self._rng.uniform(vr["pitch"][0], vr["pitch"][1], size=count),
                self._rng.uniform(vr["yaw"][0], vr["yaw"][1], size=count),
            ],
            axis=1,
        ).astype(np.float32)

    def _maybe_apply_interval_push(self, rollout_step: int):
        if (not self.domain_randomization) or len(self._push_root_dofs) < 6:
            return

        due_env_ids = np.nonzero(rollout_step >= self._push_next_step_by_env)[0].astype(np.int32)
        if due_env_ids.size == 0:
            return

        push_velocity = self._sample_push_velocity(int(due_env_ids.size))
        try:
            if self.num_envs > 1:
                self.robot.set_dofs_velocity(push_velocity, self._push_root_dofs, envs_idx=due_env_ids)
            else:
                self.robot.set_dofs_velocity(push_velocity[0], self._push_root_dofs)
        except TypeError:
            if self.num_envs > 1:
                self.robot.set_dofs_velocity(push_velocity, self._push_root_dofs, due_env_ids)
            else:
                self.robot.set_dofs_velocity(push_velocity[0], self._push_root_dofs)
        except Exception as exc:
            print(f"[WARN] Failed to apply push randomization. Disabling pushes for this run. Error: {exc}")
            self._push_next_step_by_env[:] = np.iinfo(np.int32).max
            return

        self._schedule_next_push(due_env_ids, current_step=rollout_step)

    def _reset_domain_randomization_for_rollout(self):
        if not self.domain_randomization:
            return
        env_ids = np.arange(self.num_envs, dtype=np.int32)
        self._schedule_next_push(env_ids, current_step=0)

    def _setup_domain_randomization(self):
        if not self.domain_randomization:
            return

        # 1) Randomize default joint positions (startup).
        low_j, high_j = DOMAIN_RAND_JOINT_DEFAULT_POS_RANGE
        joint_offset = self._rng.uniform(low_j, high_j, size=self._default_joint_pos_by_env.shape).astype(np.float32)
        self._default_joint_pos_by_env = (self._default_joint_pos_by_env + joint_offset).astype(np.float32)

        # 2) Randomize rigid-body friction (startup, all links).
        n_links = int(getattr(self.robot, "n_links", 0))
        link_ids = list(range(n_links))
        if n_links > 0:
            low_f, high_f = DOMAIN_RAND_FRICTION_RANGE
            friction = self._rng.uniform(low_f, high_f, size=(self.num_envs, n_links)).astype(np.float32)
            friction = _bucketize_uniform(friction, low_f, high_f, DOMAIN_RAND_FRICTION_NUM_BUCKETS)
            friction_ok = self._call_link_randomization("set_friction_ratio", friction, link_ids)
            if not friction_ok:
                print(
                    "[WARN] Genesis API does not expose set_friction_ratio for this build; "
                    "skipping physics-material friction randomization."
                )

        # 3) Randomize torso COM (startup).
        try:
            torso_link = self.robot.get_link("torso_link")
            torso_idx_local_raw = getattr(torso_link, "idx_local", None)
            if torso_idx_local_raw is None:
                torso_idx_raw = getattr(torso_link, "idx", None)
                link_start = int(getattr(self.robot, "link_start", 0))
                torso_idx_local_raw = None if torso_idx_raw is None else int(torso_idx_raw) - link_start
            torso_idx_local = -1 if torso_idx_local_raw is None else int(torso_idx_local_raw)
        except Exception:
            torso_idx_local = -1
        if torso_idx_local >= 0:
            com_shift = np.zeros((self.num_envs, 1, 3), dtype=np.float32)
            com_shift[:, 0, 0] = self._rng.uniform(
                DOMAIN_RAND_BASE_COM_RANGE["x"][0], DOMAIN_RAND_BASE_COM_RANGE["x"][1], size=self.num_envs
            ) 
            com_shift[:, 0, 1] = self._rng.uniform(
                DOMAIN_RAND_BASE_COM_RANGE["y"][0], DOMAIN_RAND_BASE_COM_RANGE["y"][1], size=self.num_envs
            )
            com_shift[:, 0, 2] = self._rng.uniform(
                DOMAIN_RAND_BASE_COM_RANGE["z"][0], DOMAIN_RAND_BASE_COM_RANGE["z"][1], size=self.num_envs
            )
            com_ok = self._call_link_randomization("set_COM_shift", com_shift, [torso_idx_local])
            if not com_ok:
                print(
                    "[WARN] Genesis API does not expose set_COM_shift for this build; "
                    "skipping base COM randomization."
                )
        else:
            print("[WARN] Could not resolve torso_link for COM randomization.")

        # 4) Prepare root-velocity push randomization (interval).
        self._push_root_dofs = self._resolve_push_root_dofs()
        if len(self._push_root_dofs) < 6:
            print("[WARN] Could not resolve 6 root DoFs for push randomization; interval pushes are disabled.")
        else:
            print("[INFO] Genesis domain randomization enabled (friction, joint defaults, torso COM, interval pushes).")

    def _init_episode_traj_buffers(self) -> list[dict[str, list[np.ndarray]]]:
        return [{key: [] for key in self.traj_data_keys} for _ in range(self.num_envs)]

    def _append_episode_traj_step(
        self,
        traj_buffers: list[dict[str, list[np.ndarray]]],
        state_batch: dict[str, np.ndarray],
        action_batch: np.ndarray,
    ):
        for env_id in range(self.num_envs):
            traj_buffers[env_id]["joint_pos"].append(state_batch["joint_pos"][env_id].astype(np.float32).copy())
            traj_buffers[env_id]["joint_vel"].append(state_batch["joint_vel"][env_id].astype(np.float32).copy())
            traj_buffers[env_id]["body_pos_w"].append(state_batch["log_body_pos_w"][env_id].astype(np.float32).copy())
            traj_buffers[env_id]["body_quat_w"].append(state_batch["log_body_quat_w"][env_id].astype(np.float32).copy())
            traj_buffers[env_id]["body_lin_vel_w"].append(state_batch["log_body_lin_vel_w"][env_id].astype(np.float32).copy())
            traj_buffers[env_id]["body_ang_vel_w"].append(state_batch["log_body_ang_vel_w"][env_id].astype(np.float32).copy())
            traj_buffers[env_id]["action"].append(action_batch[env_id].astype(np.float32).copy())

    def _finalize_episode_trajs(
        self,
        traj_buffers: list[dict[str, list[np.ndarray]]],
        rollout_id: int,
    ) -> list[dict[str, Any]]:
        finalized: list[dict[str, Any]] = []
        for env_id in range(self.num_envs):
            if len(traj_buffers[env_id]["joint_pos"]) == 0:
                continue
            traj = {
                key: np.stack(traj_buffers[env_id][key], axis=0).astype(np.float32)
                for key in self.traj_data_keys
            }
            traj["env_id"] = env_id
            traj["rollout_id"] = rollout_id
            finalized.append(traj)
        return finalized

    def _save_motion_dataset(self, trajectories: list[dict[str, Any]]) -> str | None:
        if self.output_motion_npz is None or len(trajectories) == 0:
            return None

        trajs = trajectories[: self.target_trajectories]
        motion_length = max(int(traj["joint_pos"].shape[0]) for traj in trajs)

        payload: dict[str, np.ndarray] = {
            "fps": np.array([1.0 / self.control_dt], dtype=np.float32),
        }

        body_keys = {"body_pos_w", "body_quat_w", "body_lin_vel_w", "body_ang_vel_w"}
        num_bodies = len(self.log_body_names)
        for key in ("joint_pos", "joint_vel", "body_pos_w", "body_quat_w", "body_lin_vel_w", "body_ang_vel_w", "action"):
            stacked = []
            for traj in trajs:
                seq_raw = traj[key].astype(np.float32)
                if key in body_keys:
                    seq = seq_raw
                    expected_tail_dim = 4 if key == "body_quat_w" else 3
                    if seq.ndim != 3:
                        raise AssertionError(f"Trajectory key '{key}' must be [T, num_bodies, {expected_tail_dim}], got {seq.shape}")
                    if seq.shape[1] != num_bodies or seq.shape[2] != expected_tail_dim:
                        raise AssertionError(
                            f"Trajectory key '{key}' shape mismatch: expected [T, {num_bodies}, {expected_tail_dim}], got {seq.shape}"
                        )
                else:
                    seq = seq_raw.reshape(seq_raw.shape[0], -1)
                if seq.shape[0] <= 0:
                    raise AssertionError(f"Trajectory key '{key}' has empty time dimension.")
                if seq.shape[0] < motion_length:
                    pad = np.repeat(seq[-1:, ...], motion_length - seq.shape[0], axis=0)
                    seq = np.concatenate([seq, pad], axis=0)
                elif seq.shape[0] > motion_length:
                    seq = seq[:motion_length]
                stacked.append(seq)
            payload[key] = np.stack(stacked, axis=0).astype(np.float32)

        payload["actions"] = payload["action"].copy()

        expected_num_traj = len(trajs)
        expected_shapes = {
            "joint_pos": (expected_num_traj, motion_length, self.num_joints),
            "joint_vel": (expected_num_traj, motion_length, self.num_joints),
            "action": (expected_num_traj, motion_length, self.num_actions),
            "actions": (expected_num_traj, motion_length, self.num_actions),
            "body_pos_w": (expected_num_traj, motion_length, num_bodies, 3),
            "body_quat_w": (expected_num_traj, motion_length, num_bodies, 4),
            "body_lin_vel_w": (expected_num_traj, motion_length, num_bodies, 3),
            "body_ang_vel_w": (expected_num_traj, motion_length, num_bodies, 3),
        }
        fps = payload["fps"]
        if fps.ndim != 1 or fps.shape[0] != 1 or not np.isfinite(fps).all() or float(fps[0]) <= 0.0:
            raise AssertionError(f"Invalid `fps` payload shape/value: shape={fps.shape}, value={fps}")
        for key, value in payload.items():
            if key == "fps":
                continue
            if key not in expected_shapes:
                raise AssertionError(f"Unexpected payload key '{key}'")
            if value.shape != expected_shapes[key]:
                raise AssertionError(
                    f"Payload key '{key}' shape mismatch: expected {expected_shapes[key]}, got {value.shape}"
                )
        # import ipdb;ipdb.set_trace()
        os.makedirs(os.path.dirname(self.output_motion_npz) or ".", exist_ok=True)
        np.savez(self.output_motion_npz, **payload)
        return self.output_motion_npz

    def _build_term_dims(self) -> dict[str, int]:
        return {
            "command": self.num_joints * 2,
            "motion_anchor_pos_b": 3,
            "motion_anchor_ori_b": 6,
            "base_lin_vel": 3,
            "base_ang_vel": 3,
            "joint_pos": self.num_joints,
            "joint_vel": self.num_joints,
            "actions": self.num_actions,
            "motion_joint_action": self.num_joints,
        }

    def _compute_obs_dim(self) -> int:
        obs_dim = 0
        for name, hist in zip(self.meta.observation_names, self.meta.observation_history_lengths, strict=True):
            if name not in self.term_dims:
                raise RuntimeError(f"Unsupported observation term '{name}' for sim2sim script.")
            obs_dim += self.term_dims[name] * hist

        onnx_obs_input = next(inp for inp in self.session.get_inputs() if inp.name == "obs")
        model_dim = onnx_obs_input.shape[-1]
        if isinstance(model_dim, int) and model_dim != obs_dim:
            raise RuntimeError(f"Observation dim mismatch: metadata-built={obs_dim}, ONNX-input={model_dim}")
        return obs_dim

    def _init_history(self):
        self.term_history: dict[str, deque[np.ndarray]] = {}
        for name, hist in zip(self.meta.observation_names, self.meta.observation_history_lengths, strict=True):
            dim = self.term_dims[name]
            self.term_history[name] = deque(
                (np.zeros((self.num_envs, dim), dtype=np.float32) for _ in range(hist)),
                maxlen=hist,
            )

    def _to_numpy(self, tensor: Any) -> np.ndarray:
        if hasattr(tensor, "cpu"):
            return tensor.cpu().numpy().squeeze().astype(np.float32)
        return np.asarray(tensor, dtype=np.float32).squeeze()

    def _call_genesis_1d_or_2d(self, fn, vector: np.ndarray, *args, **kwargs):
        """Call Genesis fn with a tensor shape matching scene mode.

        Non-parallel scenes expect 1D tensors, while parallel scenes expect [N, D].
        """
        tensor = torch.from_numpy(vector.astype(np.float32))
        try:
            return fn(tensor, *args, **kwargs)
        except Exception:
            # Retry with an added batch axis only for 1D inputs.
            if tensor.ndim == 1:
                return fn(tensor.unsqueeze(0), *args, **kwargs)
            raise

    def _update_reference_markers(self, ref: dict[str, np.ndarray]):
        if not self.reference_markers:
            return

        ref_positions = ref["body_pos_w"].astype(np.float32)
        for marker_idx, marker in enumerate(self.reference_markers):
            pos = ref_positions[marker_idx]
            if self.num_envs > 1:
                pos = np.repeat(pos[None, :], self.num_envs, axis=0)
            self._call_genesis_1d_or_2d(marker.set_pos, pos, zero_velocity=False)

    def _run_policy(self, obs: np.ndarray, time_step: int | np.ndarray) -> dict[str, np.ndarray]:
        obs_batch = np.asarray(obs, dtype=np.float32)
        if obs_batch.ndim == 1:
            obs_batch = obs_batch.reshape(1, -1)
        if obs_batch.ndim != 2:
            raise ValueError(f"Expected obs shape [B, D], got {obs_batch.shape}")

        batch_size = int(obs_batch.shape[0])
        if np.isscalar(time_step):
            time_input = np.full((batch_size, 1), float(time_step), dtype=np.float32)
        else:
            time_array = np.asarray(time_step, dtype=np.float32).reshape(-1)
            if time_array.size == 1 and batch_size > 1:
                time_array = np.full((batch_size,), float(time_array.item()), dtype=np.float32)
            if time_array.size != batch_size:
                raise ValueError(
                    f"time_step batch size mismatch: obs_batch={batch_size}, time_step={time_array.size}"
                )
            time_input = time_array.reshape(batch_size, 1)

        try:
            outputs = self.session.run(
                self.output_names,
                {
                    self.obs_input_name: obs_batch,
                    self.time_input_name: time_input,
                },
            )
        except Exception:
            # Fallback for ONNX models exported with fixed batch=1.
            if batch_size == 1:
                raise
            per_env_outputs = []
            for env_id in range(batch_size):
                out_env = self.session.run(
                    self.output_names,
                    {
                        self.obs_input_name: obs_batch[env_id : env_id + 1],
                        self.time_input_name: time_input[env_id : env_id + 1],
                    },
                )
                per_env_outputs.append(out_env)
            outputs = []
            for out_idx in range(len(self.output_names)):
                outputs.append(
                    np.concatenate(
                        [np.asarray(per_env_outputs[env_id][out_idx], dtype=np.float32) for env_id in range(batch_size)],
                        axis=0,
                    )
                )

        parsed: dict[str, np.ndarray] = {}
        for name, value in zip(self.output_names, outputs, strict=True):
            arr = np.asarray(value, dtype=np.float32)
            if arr.ndim == 0:
                arr = arr.reshape(batch_size, 1)
            elif arr.shape[0] != batch_size:
                if batch_size == 1:
                    arr = arr.reshape((1, *arr.shape))
                else:
                    raise RuntimeError(
                        f"Policy output '{name}' has unexpected batch dim {arr.shape[0]} (expected {batch_size})."
                    )
            parsed[name] = arr.reshape(batch_size, -1) if name == "actions" else arr
        return parsed

    def _fetch_reference_batch(self, time_step: int, batch_size: int) -> dict[str, np.ndarray]:
        zero_obs = np.zeros((batch_size, self.obs_dim_expected), dtype=np.float32)
        out = self._run_policy(zero_obs, time_step)
        return {
            "joint_pos": out["joint_pos"].astype(np.float32),
            "joint_vel": out["joint_vel"].astype(np.float32),
            "body_pos_w": out["body_pos_w"].astype(np.float32),
            "body_quat_w": out["body_quat_w"].astype(np.float32),
            "body_lin_vel_w": out["body_lin_vel_w"].astype(np.float32),
            "body_ang_vel_w": out["body_ang_vel_w"].astype(np.float32),
        }

    def _ref_for_env(self, ref_batch: dict[str, np.ndarray], env_id: int) -> dict[str, np.ndarray]:
        return {key: value[env_id].astype(np.float32) for key, value in ref_batch.items()}

    def _fetch_reference(self, time_step: int) -> dict[str, np.ndarray]:
        ref_batch = self._fetch_reference_batch(time_step, batch_size=1)
        return self._ref_for_env(ref_batch, env_id=0)

    def _reset_robot_to_reference(self, ref: dict[str, np.ndarray]):
        root_pos = ref["body_pos_w"][self.root_idx]
        root_quat = ref["body_quat_w"][self.root_idx]
        joint_pos = ref["joint_pos"]

        n_qpos = max(7, max(self.joint_qs_indices) + 1)
        qpos = np.zeros(n_qpos, dtype=np.float32)
        qpos[:3] = root_pos
        qpos[3:7] = root_quat  # Genesis expects wxyz
        for i, qs_idx in enumerate(self.joint_qs_indices):
            qpos[qs_idx] = joint_pos[i]
        qpos_cmd = np.repeat(qpos[None, :], self.num_envs, axis=0) if self.num_envs > 1 else qpos
        self._call_genesis_1d_or_2d(self.robot.set_qpos, qpos_cmd)

        # Genesis qvel packs free-joint + articulated DoFs.
        n_qvel = len(self.joint_dof_indices) + 6
        qvel = np.zeros(n_qvel, dtype=np.float32)
        qvel_cmd = np.repeat(qvel[None, :], self.num_envs, axis=0) if self.num_envs > 1 else qvel
        self._call_genesis_1d_or_2d(self.robot.set_dofs_velocity, qvel_cmd)

        self._init_history()
        self.last_action[:] = 0.0

    def _extract_state_batch(self) -> dict[str, np.ndarray]:
        joint_pos = self._to_numpy(self.robot.get_dofs_position(self.joint_dof_indices))
        joint_vel = self._to_numpy(self.robot.get_dofs_velocity(self.joint_dof_indices))
        if joint_pos.ndim == 1:
            joint_pos = joint_pos[None, :]
            joint_vel = joint_vel[None, :]

        def _extract_link_states(links: list[Any]) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
            body_pos = []
            body_quat = []
            body_lin_vel = []
            body_ang_vel = []
            for link in links:
                pos = self._to_numpy(link.get_pos())
                quat = self._to_numpy(link.get_quat())
                lin = self._to_numpy(link.get_vel())
                ang = self._to_numpy(link.get_ang())
                if pos.ndim == 1:
                    pos = pos[None, :]
                    quat = quat[None, :]
                    lin = lin[None, :]
                    ang = ang[None, :]
                body_pos.append(pos)
                body_quat.append(quat)
                body_lin_vel.append(lin)
                body_ang_vel.append(ang)
            return (
                np.stack(body_pos, axis=1),
                np.stack(body_quat, axis=1),
                np.stack(body_lin_vel, axis=1),
                np.stack(body_ang_vel, axis=1),
            )

        body_pos, body_quat, body_lin_vel, body_ang_vel = _extract_link_states(self.body_links)
        log_body_pos, log_body_quat, log_body_lin_vel, log_body_ang_vel = _extract_link_states(self.log_body_links)

        root_quat = body_quat[:, self.root_idx]
        root_lin_vel = body_lin_vel[:, self.root_idx]
        root_ang_vel = body_ang_vel[:, self.root_idx]

        return {
            "joint_pos": joint_pos.astype(np.float32),
            "joint_vel": joint_vel.astype(np.float32),
            "body_pos_w": body_pos.astype(np.float32),
            "body_quat_w": body_quat.astype(np.float32),
            "body_lin_vel_w": body_lin_vel.astype(np.float32),
            "body_ang_vel_w": body_ang_vel.astype(np.float32),
            "log_body_pos_w": log_body_pos.astype(np.float32),
            "log_body_quat_w": log_body_quat.astype(np.float32),
            "log_body_lin_vel_w": log_body_lin_vel.astype(np.float32),
            "log_body_ang_vel_w": log_body_ang_vel.astype(np.float32),
            "root_quat_w": root_quat.astype(np.float32),
            "root_lin_vel_w": root_lin_vel.astype(np.float32),
            "root_ang_vel_w": root_ang_vel.astype(np.float32),
        }

    def _state_for_env(self, state_batch: dict[str, np.ndarray], env_id: int) -> dict[str, np.ndarray]:
        return {key: value[env_id] for key, value in state_batch.items()}

    def _extract_state(self) -> dict[str, np.ndarray]:
        return self._state_for_env(self._extract_state_batch(), env_id=0)

    def _motion_action_at(self, time_step: int, batch_size: int) -> np.ndarray:
        if self.motion_actions is None:
            raise RuntimeError("motion_action requested but motion file has no `action`/`actions`.")
        idx = min(time_step, self.motion_actions.shape[0] - 1)
        action = self.motion_actions[idx].astype(np.float32)
        if action.shape[0] == self.num_actions:
            return np.repeat(action[None, :], batch_size, axis=0)
        if action.shape[0] == self.num_joints:
            return np.repeat(action[None, :], batch_size, axis=0)
        raise RuntimeError(
            f"Unexpected motion action dimension {action.shape[0]}; expected {self.num_actions} or {self.num_joints}."
        )

    def _build_observation(
        self, state_batch: dict[str, np.ndarray], ref_batch: dict[str, np.ndarray], time_step: int
    ) -> np.ndarray:
        batch_size = int(state_batch["joint_pos"].shape[0])
        if batch_size != self.num_envs:
            raise RuntimeError(f"Observation batch mismatch: got {batch_size}, expected {self.num_envs}.")

        robot_anchor_pos = state_batch["body_pos_w"][:, self.anchor_idx]
        robot_anchor_quat = state_batch["body_quat_w"][:, self.anchor_idx]
        ref_anchor_pos = ref_batch["body_pos_w"][:, self.anchor_idx]
        ref_anchor_quat = ref_batch["body_quat_w"][:, self.anchor_idx]

        rel_anchor_pos = quat_rotate_inverse_wxyz(robot_anchor_quat, ref_anchor_pos - robot_anchor_pos)
        rel_anchor_quat = quat_mul_wxyz(quat_conjugate_wxyz(robot_anchor_quat), ref_anchor_quat)
        rel_anchor_rotmat = quat_to_matrix_wxyz(rel_anchor_quat)
        rel_anchor_ori = rel_anchor_rotmat[:, :, :2].reshape(batch_size, -1)

        base_lin_vel_b = quat_rotate_inverse_wxyz(state_batch["root_quat_w"], state_batch["root_lin_vel_w"])
        base_ang_vel_b = quat_rotate_inverse_wxyz(state_batch["root_quat_w"], state_batch["root_ang_vel_w"])

        terms: dict[str, np.ndarray] = {
            "command": np.concatenate([ref_batch["joint_pos"], ref_batch["joint_vel"]], axis=1),
            "motion_anchor_pos_b": rel_anchor_pos,
            "motion_anchor_ori_b": rel_anchor_ori,
            "base_lin_vel": base_lin_vel_b,
            "base_ang_vel": base_ang_vel_b,
            "joint_pos": state_batch["joint_pos"] - self._default_joint_pos_for_batch(batch_size),
            "joint_vel": state_batch["joint_vel"],
            "actions": self.last_action.copy(),
        }

        if "motion_joint_action" in self.meta.observation_names:
            terms["motion_joint_action"] = self._motion_action_at(time_step, batch_size=batch_size)

        obs_parts = []
        for name in self.meta.observation_names:
            cur = terms[name].astype(np.float32).reshape(batch_size, -1)
            if self.add_noise and name in OBS_NOISE_UNIFORM_RANGES:
                n_min, n_max = OBS_NOISE_UNIFORM_RANGES[name]
                cur = cur + self._rng.uniform(n_min, n_max, size=cur.shape).astype(np.float32)
            self.term_history[name].append(cur)
            obs_parts.append(np.concatenate(list(self.term_history[name]), axis=1))

        obs = np.concatenate(obs_parts, axis=1).astype(np.float32)
        if obs.shape[1] != self.obs_dim_expected:
            raise RuntimeError(f"Built obs dim {obs.shape[1]} does not match expected {self.obs_dim_expected}.")
        return obs

    def _compute_joint_target(self, raw_action: np.ndarray, time_step: int) -> np.ndarray:
        processed_action = np.asarray(raw_action, dtype=np.float32).copy()
        if processed_action.ndim == 1:
            processed_action = processed_action.reshape(1, -1)
        if self.requires_motion_action:
            processed_action += self._motion_action_at(time_step, batch_size=processed_action.shape[0])
        default_joint_pos = self._default_joint_pos_for_batch(processed_action.shape[0])
        joint_target = default_joint_pos + self.meta.action_scale[None, :] * processed_action
        if self.num_envs == 1 and joint_target.shape[0] == 1:
            return joint_target[0].astype(np.float32)
        return joint_target.astype(np.float32)

    def _step_simulation(self, joint_target: np.ndarray):
        for _ in range(self.sim_decimation):
            joint_pos = self._to_numpy(self.robot.get_dofs_position(self.joint_dof_indices))
            joint_vel = self._to_numpy(self.robot.get_dofs_velocity(self.joint_dof_indices))
            torque = (joint_target - joint_pos) * self.meta.joint_stiffness - joint_vel * self.meta.joint_damping
            if self.torque_limit is not None:
                torque = np.clip(torque, -self.torque_limit, self.torque_limit)
            self._call_genesis_1d_or_2d(self.robot.control_dofs_force, torque.astype(np.float32), self.joint_dof_indices)
            self.scene.step()

    def _compute_body_relative_targets(
        self, state: dict[str, np.ndarray], ref: dict[str, np.ndarray]
    ) -> tuple[np.ndarray, np.ndarray]:
        robot_anchor_pos = state["body_pos_w"][self.anchor_idx]
        robot_anchor_quat = state["body_quat_w"][self.anchor_idx]
        ref_anchor_pos = ref["body_pos_w"][self.anchor_idx]
        ref_anchor_quat = ref["body_quat_w"][self.anchor_idx]

        delta_pos = np.repeat(robot_anchor_pos[None, :], len(self.meta.body_names), axis=0)
        delta_pos[:, 2] = ref_anchor_pos[2]
        delta_ori = yaw_quat_wxyz(quat_mul_wxyz(robot_anchor_quat, quat_conjugate_wxyz(ref_anchor_quat)))
        delta_ori_batch = np.repeat(delta_ori[None, :], len(self.meta.body_names), axis=0)

        ref_body_pos = ref["body_pos_w"]
        ref_body_quat = ref["body_quat_w"]
        ref_anchor_repeat = np.repeat(ref_anchor_pos[None, :], len(self.meta.body_names), axis=0)

        body_pos_relative = delta_pos + quat_rotate_wxyz(delta_ori, ref_body_pos - ref_anchor_repeat)
        body_quat_relative = quat_mul_wxyz(delta_ori_batch, ref_body_quat)
        return body_pos_relative, body_quat_relative

    def _termination_check(
        self, state: dict[str, np.ndarray], ref: dict[str, np.ndarray], body_pos_relative: np.ndarray
    ) -> tuple[bool, str]:
        robot_anchor_pos = state["body_pos_w"][self.anchor_idx]
        robot_anchor_quat = state["body_quat_w"][self.anchor_idx]
        ref_anchor_pos = ref["body_pos_w"][self.anchor_idx]
        ref_anchor_quat = ref["body_quat_w"][self.anchor_idx]

        # bad_anchor_pos_z_only threshold
        if abs(ref_anchor_pos[2] - robot_anchor_pos[2]) > 0.5:
            return True, "anchor_pos_z"

        # bad_anchor_ori threshold (projected gravity difference)
        gravity = np.array([0.0, 0.0, -1.0], dtype=np.float32)
        motion_pg = quat_rotate_inverse_wxyz(ref_anchor_quat, gravity)
        robot_pg = quat_rotate_inverse_wxyz(robot_anchor_quat, gravity)
        if abs(motion_pg[2] - robot_pg[2]) > 0.8:
            return True, "anchor_ori"

        # bad_motion_body_pos_z_only for feet/wrists
        # if self.ee_body_indices:
        #     z_err = np.abs(body_pos_relative[self.ee_body_indices, 2] - state["body_pos_w"][self.ee_body_indices, 2])
        #     if np.any(z_err > 0.25):
        #         return True, "ee_body_pos_z"

        return False, "completed"

    def _tracking_metrics(self, state: dict[str, np.ndarray], ref: dict[str, np.ndarray]) -> dict[str, float | str]:
        robot_anchor_pos = state["body_pos_w"][self.anchor_idx]
        robot_anchor_quat = state["body_quat_w"][self.anchor_idx]
        ref_anchor_pos = ref["body_pos_w"][self.anchor_idx]
        ref_anchor_quat = ref["body_quat_w"][self.anchor_idx]

        body_pos_relative, body_quat_relative = self._compute_body_relative_targets(state, ref)

        err_anchor_pos = float(np.linalg.norm(ref_anchor_pos - robot_anchor_pos))
        err_anchor_rot = float(quat_error_magnitude_wxyz(ref_anchor_quat, robot_anchor_quat))
        err_body_pos = float(np.linalg.norm(body_pos_relative - state["body_pos_w"], axis=-1).mean())
        err_body_rot = float(quat_error_magnitude_wxyz(body_quat_relative, state["body_quat_w"]).mean())
        err_joint_pos = float(np.linalg.norm(ref["joint_pos"] - state["joint_pos"]))
        err_joint_vel = float(np.linalg.norm(ref["joint_vel"] - state["joint_vel"]))

        # Positive tracking-only rewards from tracking_env_cfg
        rew_anchor_pos = float(np.exp(-(np.square(ref_anchor_pos - robot_anchor_pos).sum()) / (0.3**2)))
        rew_anchor_ori = float(np.exp(-(err_anchor_rot**2) / (0.4**2)))

        body_pos_sq = np.square(body_pos_relative - state["body_pos_w"]).sum(axis=-1).mean()
        rew_body_pos = float(np.exp(-body_pos_sq / (0.3**2)))

        body_rot_sq = np.square(quat_error_magnitude_wxyz(body_quat_relative, state["body_quat_w"])).mean()
        rew_body_ori = float(np.exp(-body_rot_sq / (0.4**2)))

        body_lin_sq = np.square(ref["body_lin_vel_w"] - state["body_lin_vel_w"]).sum(axis=-1).mean()
        rew_body_lin_vel = float(np.exp(-body_lin_sq / (1.0**2)))

        body_ang_sq = np.square(ref["body_ang_vel_w"] - state["body_ang_vel_w"]).sum(axis=-1).mean()
        rew_body_ang_vel = float(np.exp(-body_ang_sq / (3.14**2)))

        tracking_reward = (
            0.5 * rew_anchor_pos
            + 0.5 * rew_anchor_ori
            + 1.0 * rew_body_pos
            + 1.0 * rew_body_ori
            + 1.0 * rew_body_lin_vel
            + 1.0 * rew_body_ang_vel
        )

        terminated, reason = self._termination_check(state, ref, body_pos_relative)
        return {
            "error_anchor_pos": err_anchor_pos,
            "error_anchor_rot": err_anchor_rot,
            "error_body_pos": err_body_pos,
            "error_body_rot": err_body_rot,
            "error_joint_pos": err_joint_pos,
            "error_joint_vel": err_joint_vel,
            "rew_tracking_anchor_pos": rew_anchor_pos,
            "rew_tracking_anchor_ori": rew_anchor_ori,
            "rew_tracking_body_pos": rew_body_pos,
            "rew_tracking_body_ori": rew_body_ori,
            "rew_tracking_body_lin_vel": rew_body_lin_vel,
            "rew_tracking_body_ang_vel": rew_body_ang_vel,
            "tracking_reward_total": tracking_reward,
            "terminated": float(1.0 if terminated else 0.0),
            "termination_reason": reason,
        }

    def evaluate(self, run_timestamp: str, video_name: str | None = None) -> dict[str, Any]:
        if self.cam is not None:
            self.cam.start_recording()

        metric_sums: dict[str, float] = defaultdict(float)
        rollout_metric_values_all: dict[str, list[float]] = defaultdict(list)
        rollout_metric_values_succ: dict[str, list[float]] = defaultdict(list)
        termination_reason = "completed"
        total_steps = 0
        rollout_count = 0
        metrics_enabled = self.compute_metrics
        metric_target_envs = self.metric_num_envs if metrics_enabled else 0
        metric_envs_done = 0
        success_metric_envs = 0
        collected_trajectories: list[dict[str, Any]] = []
        record_motion_enabled = self.record_motion and self.output_motion_npz is not None
        target_for_npz = self.target_trajectories if record_motion_enabled else 0
        traj_pbar = None
        metrics_pbar = None
        step_pbar = None
        target_rollouts = max(target_for_npz, metric_target_envs)
        estimated_rollouts = (target_rollouts + self.num_envs - 1) // self.num_envs if target_rollouts > 0 else 0
        if record_motion_enabled and target_for_npz > 0:
            if tqdm is not None:
                traj_pbar = tqdm(
                    total=target_for_npz, desc="Collect trajectories", unit="traj", leave=True, dynamic_ncols=True
                )
            else:
                print(f"[INFO] Collecting trajectories: 0/{target_for_npz}")
        if metrics_enabled and metric_target_envs > 0:
            if tqdm is not None:
                metrics_pbar = tqdm(
                    total=metric_target_envs, desc="Compute metrics", unit="env", leave=True, dynamic_ncols=True
                )
            else:
                print(f"[INFO] Computing metrics: 0/{metric_target_envs}")
        if tqdm is not None:
            step_total = estimated_rollouts * self.max_steps if estimated_rollouts > 0 else None
            step_pbar = tqdm(
                total=step_total,
                desc="Simulate rollouts",
                unit="step",
                leave=True,
                dynamic_ncols=True,
                mininterval=0.5,
            )

        while True:
            active_rollout_index = rollout_count + 1
            ref0_batch = self._fetch_reference_batch(self.start_timestep, batch_size=self.num_envs)
            ref0 = self._ref_for_env(ref0_batch, env_id=0)
            self._reset_robot_to_reference(ref0)
            self._reset_domain_randomization_for_rollout()
            self._update_reference_markers(ref0)
            state_batch = self._extract_state_batch()
            obs = self._build_observation(state_batch, ref0_batch, time_step=self.start_timestep)
            traj_buffers = self._init_episode_traj_buffers()
            steps_this_rollout = 0
            rollout_body_pos_pred: list[np.ndarray] = []
            rollout_body_pos_gt: list[np.ndarray] = []
            env_done = np.zeros(self.num_envs, dtype=bool)
            env_end_step = np.full(self.num_envs, self.max_steps, dtype=np.int32)

            for t_step in range(self.max_steps):
                ref_step = self.start_timestep + t_step
                policy_out = self._run_policy(obs, ref_step)
                action_batch = policy_out["actions"].astype(np.float32)
                ref_batch = {
                    "joint_pos": policy_out["joint_pos"].astype(np.float32),
                    "joint_vel": policy_out["joint_vel"].astype(np.float32),
                    "body_pos_w": policy_out["body_pos_w"].astype(np.float32),
                    "body_quat_w": policy_out["body_quat_w"].astype(np.float32),
                    "body_lin_vel_w": policy_out["body_lin_vel_w"].astype(np.float32),
                    "body_ang_vel_w": policy_out["body_ang_vel_w"].astype(np.float32),
                }
                ref = self._ref_for_env(ref_batch, env_id=0)
                self._update_reference_markers(ref)

                joint_target = self._compute_joint_target(action_batch, time_step=ref_step)
                self._maybe_apply_interval_push(t_step)
                self._step_simulation(joint_target)
                state_batch = self._extract_state_batch()
                self._append_episode_traj_step(traj_buffers, state_batch, action_batch)
                state = self._state_for_env(state_batch, env_id=0)
                if metrics_enabled:
                    rollout_body_pos_pred.append(state_batch["body_pos_w"].astype(np.float32).copy())
                    rollout_body_pos_gt.append(ref_batch["body_pos_w"].astype(np.float32).copy())
                    for env_id in range(self.num_envs):
                        if env_done[env_id]:
                            continue
                        env_state = self._state_for_env(state_batch, env_id=env_id)
                        env_ref = self._ref_for_env(ref_batch, env_id=env_id)
                        env_body_pos_relative, _ = self._compute_body_relative_targets(env_state, env_ref)
                        env_terminated, env_reason = self._termination_check(env_state, env_ref, env_body_pos_relative)
                        if env_terminated:
                            env_done[env_id] = True
                            env_end_step[env_id] = t_step + 1
                            if env_id == 0:
                                termination_reason = env_reason

                step_metrics = self._tracking_metrics(state, ref)
                terminated = bool(step_metrics.pop("terminated"))
                step_reason = step_metrics.pop("termination_reason")
                if not metrics_enabled or terminated:
                    termination_reason = step_reason
                for key, value in step_metrics.items():
                    metric_sums[key] += float(value)

                self.last_action = action_batch.copy()
                total_steps += 1
                steps_this_rollout += 1
                if step_pbar is not None:
                    step_pbar.update(1)
                    if (
                        t_step == 0
                        or (t_step + 1) % 10 == 0
                        or (not metrics_enabled and terminated)
                        or (metrics_enabled and bool(np.all(env_done)))
                        or t_step + 1 >= self.max_steps
                    ):
                        step_pbar.set_postfix(
                            rollout=active_rollout_index,
                            rollout_step=f"{t_step + 1}/{self.max_steps}",
                            traj_saved=len(collected_trajectories),
                            done_envs=int(env_done.sum()),
                            refresh=False,
                        )

                if self.cam is not None:
                    root_pos = state["body_pos_w"][self.root_idx]
                    self.cam.set_pose(
                        pos=(float(root_pos[0] + 2.5), float(root_pos[1]), 1.6),
                        lookat=(float(root_pos[0]), float(root_pos[1]), float(root_pos[2] + 0.3)),
                    )
                    self.cam.render()

                if not metrics_enabled and terminated:
                    break

                if t_step + 1 >= self.max_steps:
                    break

                if metrics_enabled and bool(np.all(env_done)):
                    break

                ref_next_step = ref_step + 1
                ref_next_batch = self._fetch_reference_batch(ref_next_step, batch_size=self.num_envs)
                obs = self._build_observation(state_batch, ref_next_batch, time_step=ref_next_step)

            rollout_id = rollout_count
            rollout_count += 1
            if metrics_enabled and len(rollout_body_pos_pred) > 0 and metric_envs_done < metric_target_envs:
                pred_pos_rollout = np.stack(rollout_body_pos_pred, axis=0)
                gt_pos_rollout = np.stack(rollout_body_pos_gt, axis=0)
                for env_id in range(self.num_envs):
                    if metric_envs_done >= metric_target_envs:
                        break
                    traj_len = int(np.clip(env_end_step[env_id], 1, pred_pos_rollout.shape[0]))
                    pred_pos = pred_pos_rollout[:traj_len, env_id]
                    gt_pos = gt_pos_rollout[:traj_len, env_id]
                    # Remove static env-spacing translation so global metrics match reference frame.
                    spacing_offset = pred_pos[0, self.root_idx] - gt_pos[0, self.root_idx]
                    pred_pos_aligned = pred_pos - spacing_offset[None, None, :]
                    lite_metrics = _compute_metrics_lite(pred_pos_aligned, gt_pos, root_idx=self.root_idx)
                    is_success = int(env_end_step[env_id]) >= max(self.max_steps - 5, 1)
                    env_metrics = {
                        "mpjpe": (
                            float(lite_metrics["mpjpe_g"].mean()) if lite_metrics["mpjpe_g"].size > 0 else float("nan")
                        ),
                        "mpjpe_l": (
                            float(lite_metrics["mpjpe_l"].mean()) if lite_metrics["mpjpe_l"].size > 0 else float("nan")
                        ),
                        "accel_dist": (
                            float(lite_metrics["accel_dist"].mean())
                            if lite_metrics["accel_dist"].size > 0
                            else float("nan")
                        ),
                        "vel_dist": (
                            float(lite_metrics["vel_dist"].mean()) if lite_metrics["vel_dist"].size > 0 else float("nan")
                        ),
                    }
                    for key, value in env_metrics.items():
                        rollout_metric_values_all[key].append(value)
                        if is_success:
                            rollout_metric_values_succ[key].append(value)
                    if is_success:
                        success_metric_envs += 1
                    metric_envs_done += 1
                    if metrics_pbar is not None:
                        metrics_pbar.update(1)
                    elif metric_target_envs > 0:
                        print(f"[INFO] Computing metrics: {metric_envs_done}/{metric_target_envs}")

            if record_motion_enabled:
                prev_count = len(collected_trajectories)
                collected_trajectories.extend(self._finalize_episode_trajs(traj_buffers, rollout_id=rollout_id))
                gained = len(collected_trajectories) - prev_count
                if gained > 0 and target_for_npz > 0:
                    if traj_pbar is not None:
                        remaining = max(target_for_npz - int(traj_pbar.n), 0)
                        traj_pbar.update(min(gained, remaining))
                    else:
                        shown = min(len(collected_trajectories), target_for_npz)
                        print(f"[INFO] Collecting trajectories: {shown}/{target_for_npz}")
            if step_pbar is not None:
                step_pbar.set_postfix(
                    rollout=rollout_count,
                    rollout_step=f"{steps_this_rollout}/{self.max_steps}",
                    traj_saved=len(collected_trajectories),
                    done_envs=int(env_done.sum()),
                    refresh=False,
                )

            if metrics_enabled and metric_envs_done >= metric_target_envs:
                break
            if not record_motion_enabled and not metrics_enabled:
                break
            if target_for_npz > 0 and len(collected_trajectories) >= target_for_npz:
                break
            if steps_this_rollout <= 0:
                break

        if self.cam is not None:
            filename = video_name or f"logs/sim2sim_eval/{NEXT_LAB_DATE}/{run_timestamp}_genesis_eval.mp4"
            self.cam.stop_recording(save_to_filename=filename, fps=round(1.0 / self.control_dt))
        if step_pbar is not None:
            step_pbar.close()
        if traj_pbar is not None:
            traj_pbar.close()
        if metrics_pbar is not None:
            metrics_pbar.close()
        motion_npz_path = self._save_motion_dataset(collected_trajectories) if record_motion_enabled else None

        out = {
            "evaluation_seed": self.experiment_seed,
            "policy_path": self.policy_path,
            "motion_file": self.motion_file,
            "num_envs": self.num_envs,
            "domain_randomization": int(self.domain_randomization),
            "steps": total_steps,
            "max_steps": self.max_steps,
            "start_timestep": self.start_timestep,
            "reference_motion_length_steps": self.reference_motion_length_steps,
            "rollouts": rollout_count,
            "motion_completion_pct": (
                100.0 * total_steps / (self.max_steps * rollout_count)
                if self.max_steps > 0 and rollout_count > 0
                else 0.0
            ),
            "terminated": 1 if termination_reason != "completed" else 0,
            "termination_reason": termination_reason,
            "collected_trajectories": len(collected_trajectories),
            "target_trajectories": target_for_npz,
        }
        if motion_npz_path is not None:
            out["output_motion_npz"] = motion_npz_path
        if total_steps > 0:
            for key, value in metric_sums.items():
                out[f"{key}_mean"] = value / total_steps

        out["compute_metrics"] = int(metrics_enabled)
        if metrics_enabled:
            out["metric_num_envs_target"] = metric_target_envs
            out["metric_num_envs_done"] = metric_envs_done
            out["success"] = (
                100.0 * float(success_metric_envs) / float(metric_envs_done) if metric_envs_done > 0 else 0.0
            )
            out["success_envs"] = success_metric_envs

            def _safe_mean_std(values: list[float]) -> tuple[float, float]:
                arr = np.asarray(values, dtype=np.float32)
                arr = arr[np.isfinite(arr)]
                if arr.size == 0:
                    return float("nan"), float("nan")
                return float(arr.mean()), float(arr.std())

            for metric_name in ("mpjpe", "mpjpe_l", "accel_dist", "vel_dist"):
                mean_all, std_all = _safe_mean_std(rollout_metric_values_all[metric_name])
                mean_succ, std_succ = _safe_mean_std(rollout_metric_values_succ[metric_name])
                out[f"{metric_name}_mean"] = mean_all
                out[f"{metric_name}_std"] = std_all
                out[f"{metric_name}_succ_mean"] = mean_succ
                out[f"{metric_name}_succ_std"] = std_succ

        return out


def _write_csv(path: str, row: dict[str, Any]):
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(row.keys()))
        writer.writeheader()
        writer.writerow(row)


def _write_json(path: str, row: dict[str, Any]):
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(row, f, indent=2, sort_keys=True)


def _append_timestamp_to_path(path: str, timestamp: str) -> str:
    directory = os.path.dirname(path)
    filename = os.path.basename(path)
    stem, ext = os.path.splitext(filename)
    stamped = f"{stem}_{timestamp}{ext}"
    return os.path.join(directory, stamped)


DEFAULT_G1_URDF = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "source",
    "whole_body_tracking",
    "whole_body_tracking",
    "assets",
    "unitree_description",
    "urdf",
    "g1",
    "main.urdf",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Genesis sim2sim evaluator for whole_body_tracking ONNX policies.")
    parser.add_argument("--policy_path", type=str, required=True, help="Path to exported ONNX policy.")
    parser.add_argument(
        "--dataset_yaml",
        type=str,
        default=None,
        help="Deprecated (ignored). Kept for compatibility with older TWIST-style invocation.",
    )
    parser.add_argument(
        "--urdf_file",
        type=str,
        default=DEFAULT_G1_URDF,
        help="Path to robot URDF used by Genesis (default: repo G1 URDF path).",
    )
    parser.add_argument(
        "--xml_file",
        type=str,
        default=None,
        help="Deprecated MJCF XML path fallback. Prefer --urdf_file.",
    )
    parser.add_argument(
        "--motion_file",
        type=str,
        default=None,
        help="Optional motion.npz path. Required if policy uses `motion_joint_action` observation term.",
    )
    parser.add_argument(
        "--output_motion_npz",
        type=str,
        default=None,
        help=(
            "Optional path to save motion trajectories for delta-action training. "
            "Saves one NPZ: joints/actions are (num_traj, motion_length, dim), "
            "and body tensors are (num_traj, motion_length, num_bodies, 3/4)."
        ),
    )
    parser.add_argument(
        "--record_motion",
        action="store_true",
        help="Enable trajectory recording to --output_motion_npz (disabled by default).",
    )
    parser.add_argument(
        "--target_trajectories",
        type=int,
        default=1,
        help="Number of trajectories to collect into --output_motion_npz (default: 1).",
    )
    parser.add_argument("--output_csv", type=str, default=None, help="Output CSV path (single-row summary).")
    parser.add_argument("--output_json", type=str, default=None, help="Optional JSON output path.")
    parser.add_argument("--backend", type=str, default="gpu", choices=["cpu", "gpu"], help="Genesis backend.")
    parser.add_argument("--policy_device", type=str, default="cuda", help="ONNXRuntime device hint: cpu or cuda.")
    parser.add_argument("--device", dest="policy_device", help="Alias for --policy_device.")
    parser.add_argument("--num_envs", type=int, default=1, help="Number of parallel Genesis environments.")
    parser.add_argument("--sim_dt", type=float, default=0.001, help="Genesis simulation dt.")
    parser.add_argument("--control_dt", type=float, default=0.02, help="Policy control dt.")
    parser.add_argument(
        "--start_timestep",
        type=int,
        default=0,
        help="Reference-motion timestep to start rollout from (default: 0).",
    )
    parser.add_argument(
        "--max_steps",
        type=int,
        default=None,
        help=(
            "Deprecated. Ignored in Genesis evaluator; rollout horizon always matches remaining reference "
            "length from --start_timestep."
        ),
    )
    parser.add_argument(
        "--torque_limit",
        type=float,
        default=None,
        help="Optional symmetric torque clip for manual PD torques.",
    )
    parser.add_argument("--record_video", action="store_true", help="Record evaluation video.")
    parser.add_argument("--viewer", action="store_true", help="Show Genesis viewer during evaluation.")
    parser.add_argument(
        "--compute_metrics",
        action="store_true",
        help="Enable ASAP-style motion metrics (MPJPE/velocity/acceleration).",
    )
    parser.add_argument(
        "--metric_num_envs",
        type=int,
        default=1,
        help="Number of environment trajectories to evaluate for metrics before exiting.",
    )
    parser.add_argument(
        "--add_noise",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Add training-style uniform noise to policy observation terms (default: true).",
    )
    parser.add_argument(
        "--domain_randomization",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Apply Isaac-matching domain randomization in Genesis (default: true).",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help=(
            "If set, seeds Python/NumPy/PyTorch, observation noise / domain-RNG, and Genesis (when supported). "
            "Use together with --backend cpu --policy_device cpu for the most repeatable metrics."
        ),
    )
    parser.add_argument(
        "--show_reference",
        action="store_true",
        help="Visualize reference body trajectory as white dots (one sphere per reference body).",
    )
    parser.add_argument(
        "--reference_marker_radius",
        type=float,
        default=0.05,
        help="Radius of white reference marker spheres.",
    )
    parser.add_argument("--video_name", type=str, default=None, help="Optional output video filename.")
    return parser.parse_args()


def main():
    args = parse_args()
    if not os.path.isfile(args.policy_path):
        raise FileNotFoundError(f"Policy not found: {args.policy_path}")
    if args.urdf_file is not None and not os.path.isfile(args.urdf_file):
        if args.xml_file is None:
            raise FileNotFoundError(
                f"URDF file not found: {args.urdf_file}\n"
                "Provide --urdf_file pointing to G1 URDF (recommended), or provide --xml_file fallback."
            )
        args.urdf_file = None
    if args.xml_file is not None and not os.path.isfile(args.xml_file):
        raise FileNotFoundError(f"XML file not found: {args.xml_file}")
    if args.motion_file is not None and not os.path.isfile(args.motion_file):
        raise FileNotFoundError(f"Motion file not found: {args.motion_file}")
    effective_compute_metrics = bool(args.compute_metrics or args.record_motion)
    effective_metric_num_envs = args.target_trajectories if args.record_motion else args.metric_num_envs
    if effective_compute_metrics and effective_metric_num_envs <= 0:
        raise ValueError(f"--metric_num_envs must be > 0. Got {effective_metric_num_envs}")

    policy_name = os.path.basename(args.policy_path).replace(".onnx", "")
    run_timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    output_csv = None
    output_json = None
    if effective_compute_metrics:
        output_csv = args.output_csv
        if output_csv is None:
            output_csv = os.path.join("logs", "sim2sim_eval", NEXT_LAB_DATE, f"{policy_name}_genesis_metrics.csv")
        output_csv = _append_timestamp_to_path(output_csv, run_timestamp)

        output_json = args.output_json
        if output_json is None:
            output_json = os.path.join("logs", "sim2sim_eval", NEXT_LAB_DATE, f"{policy_name}_genesis_metrics.json")
        output_json = _append_timestamp_to_path(output_json, run_timestamp)

    output_motion_npz = None
    if args.record_motion:
        output_motion_npz = args.output_motion_npz
        if output_motion_npz is None:
            output_motion_npz = os.path.join("logs", "sim2sim_eval", NEXT_LAB_DATE, f"{policy_name}_motion_dataset.npz")
        output_motion_npz = _append_timestamp_to_path(output_motion_npz, run_timestamp)

    evaluator = Sim2SimEvaluatorGenesis(
        policy_path=args.policy_path,
        urdf_file=args.urdf_file,
        xml_file=args.xml_file,
        motion_file=args.motion_file,
        backend=args.backend,
        policy_device=args.policy_device,
        sim_dt=args.sim_dt,
        control_dt=args.control_dt,
        max_steps=args.max_steps,
        start_timestep=args.start_timestep,
        torque_limit=args.torque_limit,
        record_video=args.record_video,
        viewer=args.viewer,
        num_envs=args.num_envs,
        show_reference=True,
        reference_marker_radius=args.reference_marker_radius,
        output_motion_npz=output_motion_npz,
        target_trajectories=args.target_trajectories,
        record_motion=args.record_motion,
        compute_metrics=effective_compute_metrics,
        metric_num_envs=effective_metric_num_envs,
        add_noise=args.add_noise,
        domain_randomization=args.domain_randomization,
        experiment_seed=args.seed,
    )

    result = evaluator.evaluate(run_timestamp, video_name=args.video_name)
    if output_csv is not None:
        _write_csv(output_csv, result)
    if output_json is not None:
        _write_json(output_json, result)

    print("\n=== Genesis Sim2Sim Evaluation Summary ===")
    for key in sorted(result.keys()):
        print(f"{key}: {result[key]}")
    if output_csv is not None:
        print(f"\nSaved CSV: {output_csv}")
    if output_json is not None:
        print(f"Saved JSON: {output_json}")
    if "output_motion_npz" in result:
        print(f"Saved motion NPZ: {result['output_motion_npz']}")


if __name__ == "__main__":
    main()
